// lib/render_md.jsx — Markdown report renderer.
//
// Takes the in-memory report object (same shape as the JSON we write
// to /tmp/ai-validate-report.json) and returns a Markdown string.
//
// The artist reads the .md, not the .json. Keep this file focused on
// presentation; do not perform any analysis here.

function renderMarkdown(report) {
    var lines = [];
    var basename = filenameOf(report.file || "(untitled)");
    var isFix = (report.mode === "fix");

    lines.push("# AI validation — " + basename + (isFix ? " (FIX MODE)" : ""));
    lines.push("");
    lines.push("_Generated by `tools/ai-validate`. Re-run after fixing to refresh._");
    lines.push("");
    lines.push("- **File:** `" + (report.file || "(untitled)") + "`");
    lines.push("- **Mode:** " + report.mode);
    if (report.snapshot && report.snapshot.bricks) {
        lines.push("- **Brick layers scanned:** " + report.snapshot.bricks.length);
    }
    var s = report.summary || { total: 0, by_severity: {}, by_kind: {} };
    var nErr  = s.by_severity.error   || 0;
    var nWarn = s.by_severity.warning || 0;
    var label = isFix ? "Remaining findings" : "Findings";
    lines.push("- **" + label + ":** **" + (s.total || 0) + "** — " +
               nErr + " errors, " + nWarn + " warnings");
    if (isFix && report.fixes) {
        var nApplied = report.fixes.applied ? report.fixes.applied.length : 0;
        lines.push("- **Fixes applied:** " + nApplied);
    }
    lines.push("");

    if (report.error) {
        lines.push("> :warning: Script error: " + report.error);
        lines.push("");
    }

    if (isFix && report.fixes) {
        renderFixesSection(lines, report.fixes);
    }

    if (!report.findings || report.findings.length === 0) {
        if (isFix) {
            lines.push("## Remaining findings");
            lines.push("");
            lines.push("No findings remain after auto-fix. Save the file to commit changes.");
        } else {
            lines.push("No findings. Source file is clean.");
        }
        return lines.join("\n") + "\n";
    }

    // Group findings by kind, severity preserved.
    var byKind = {};
    for (var i = 0; i < report.findings.length; i++) {
        var f = report.findings[i];
        if (!byKind[f.kind]) byKind[f.kind] = [];
        byKind[f.kind].push(f);
    }
    var ordered = orderKinds(byKind);

    lines.push(isFix ? "## Remaining findings" : "## Summary");
    lines.push("");
    lines.push("| Severity | Kind | Count |");
    lines.push("|---|---|---|");
    for (var j = 0; j < ordered.length; j++) {
        var kind = ordered[j];
        var arr = byKind[kind];
        lines.push("| " + arr[0].severity + " | `" + kind + "` | " + arr.length + " |");
    }
    lines.push("");

    for (var k = 0; k < ordered.length; k++) {
        renderKindSection(lines, ordered[k], byKind[ordered[k]]);
    }

    lines.push("---");
    lines.push("");
    lines.push("_Notes:_");
    lines.push("- Brick names are Illustrator's layer names (e.g. `Layer 81`).");
    lines.push("- 1 pymu = 1 point in this project.");
    lines.push("- `error`-level findings will fail CI once Phase 4 is wired in.");
    lines.push("- `warning`-level findings are advisory; the artist decides.");

    return lines.join("\n") + "\n";
}

function filenameOf(p) {
    var i = p.lastIndexOf("/");
    return i >= 0 ? p.substring(i + 1) : p;
}

function renderFixesSection(lines, fixes) {
    var applied = fixes.applied || [];
    if (applied.length === 0) {
        lines.push("## Fixes");
        lines.push("");
        lines.push("No deterministic fixes applied (nothing eligible).");
        lines.push("");
        return;
    }
    // Group applied fixes by action.
    var byAction = {};
    for (var i = 0; i < applied.length; i++) {
        var a = applied[i];
        if (!byAction[a.action]) byAction[a.action] = [];
        byAction[a.action].push(a);
    }
    lines.push("## Fixes applied");
    lines.push("");
    for (var action in byAction) {
        if (!byAction.hasOwnProperty(action)) continue;
        var arr = byAction[action];
        lines.push("### `" + action + "` × " + arr.length);
        lines.push("");
        if (action === "close_path") {
            lines.push("Set `pathItem.closed = true`. Illustrator draws an implicit straight closing segment for any non-zero gap.");
            lines.push("");
            lines.push("| Brick | Sub-path | Pre-fix gap (pymu) |");
            lines.push("|---|---|---|");
            for (var k = 0; k < arr.length; k++) {
                var f = arr[k];
                var gap = (f.gap_pymu == null) ? "—" : f.gap_pymu.toFixed(3);
                lines.push("| `" + f.brick + "` | " + f.sub_path + " | " + gap + " |");
            }
        } else if (action === "merge_subpymu") {
            lines.push("Two anchors on a sub-pymu edge merged into one. The survivor is the anchor whose coordinates appear more often in the brick (i.e. matches the canonical grid).");
            lines.push("");
            lines.push("| Brick | Sub-path | Edge (pymu) | Kept | Dropped |");
            lines.push("|---|---|---|---|---|");
            for (var n = 0; n < arr.length; n++) {
                var g = arr[n];
                var len = (g.edge_len_pymu == null) ? "—" : g.edge_len_pymu.toFixed(3);
                lines.push("| `" + g.brick + "` | " + g.sub_path + " | " + len +
                           " | " + fmtPt(g.kept_anchor) + " | " + fmtPt(g.dropped_anchor) + " |");
            }
        } else {
            lines.push("| Brick | Sub-path |");
            lines.push("|---|---|");
            for (var m = 0; m < arr.length; m++) {
                lines.push("| `" + arr[m].brick + "` | " + arr[m].sub_path + " |");
            }
        }
        lines.push("");
    }
}

function orderKinds(byKind) {
    var errors = [], warnings = [];
    for (var k in byKind) {
        if (!byKind.hasOwnProperty(k)) continue;
        if (byKind[k][0].severity === "error") errors.push(k);
        else warnings.push(k);
    }
    var byCountDesc = function (a, b) { return byKind[b].length - byKind[a].length; };
    errors.sort(byCountDesc);
    warnings.sort(byCountDesc);
    return errors.concat(warnings);
}

function renderKindSection(lines, kind, arr) {
    lines.push("## " + arr[0].severity + ": `" + kind + "` × " + arr.length);
    lines.push("");
    lines.push(kindBlurb(kind));
    lines.push("");
    var renderer = TABLE_RENDERERS[kind] || renderGenericTable;
    renderer(lines, arr);
    lines.push("");
}

function kindBlurb(kind) {
    var blurbs = {
        unclosed_path:
            "Open sub-paths whose start anchor doesn't meet the last segment endpoint. " +
            "Currently masked by the `ai_parser` auto-close workaround (commit f22a52c); " +
            "fix in source so the workaround can be removed.",
        unclosed_path_zero_gap:
            "Sub-path is visually closed (start == end anchor) but Illustrator's `closed` " +
            "flag is `false`. Phase 2 `--fix` will set the flag with no shape change.",
        degenerate_path:
            "Sub-path has fewer than 3 anchors — cannot form a brick polygon.",
        degenerate_area:
            "Sub-path's signed area is below 1 pymu² — likely a stray click or " +
            "near-collapsed shape.",
        sub_pymu_edge:
            "Sub-path contains an edge shorter than 1 pymu — usually a staircase " +
            "artefact from imprecise snapping. The artist must decide whether to merge " +
            "the offending vertices.",
        multi_object_layer:
            "Brick layer contains 2+ sub-paths whose bboxes don't overlap — likely " +
            "multiple independent bricks merged under one layer name.",
        multi_grid_drift:
            "Anchors that should sit on the same nominal grid line are split across " +
            "more than one value across bricks (cluster span > 0.1 pymu). Phase 2 " +
            "`--fix` will snap each cluster to its most-popular value.",
        intra_brick_drift:
            "Within a single brick, anchors that should share an axis value differ by " +
            "> 0.1 pymu. Often the result of editing one corner without updating the " +
            "matching corner.",
        corner_jitter:
            "Two bricks have anchors within 1 pymu of each other but not bit-identical " +
            "— they nominally share a corner but disagree by enough to drift the " +
            "runtime mesh.",
        brick_bbox_contained:
            "One brick's bounding box is fully inside another's. May be intentional " +
            "(window in wall) or a stray duplicate; review by hand.",
        missing_top_layer:
            "Expected top-level layer is absent from the document.",
        empty_top_layer:
            "Expected top-level layer exists but is empty."
    };
    return blurbs[kind] || "_(no description)_";
}

// --- per-kind table renderers ------------------------------------------

var TABLE_RENDERERS = {};

TABLE_RENDERERS.unclosed_path = function (lines, arr) {
    lines.push("| Brick | Sub-path | Anchors | Gap (pymu) | First | Last |");
    lines.push("|---|---|---|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | " + f.sub_path + " | " + f.anchor_count +
                   " | " + f.gap_pymu.toFixed(3) +
                   " | " + fmtPt(f.first) + " | " + fmtPt(f.last) + " |");
    }
};
TABLE_RENDERERS.unclosed_path_zero_gap = TABLE_RENDERERS.unclosed_path;

TABLE_RENDERERS.degenerate_path = function (lines, arr) {
    lines.push("| Brick | Sub-path | Anchors |");
    lines.push("|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | " + f.sub_path + " | " + f.anchor_count + " |");
    }
};

TABLE_RENDERERS.degenerate_area = function (lines, arr) {
    lines.push("| Brick | Sub-path | Area (pymu²) |");
    lines.push("|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | " + f.sub_path + " | " + f.area_pymu2.toFixed(3) + " |");
    }
};

TABLE_RENDERERS.sub_pymu_edge = function (lines, arr) {
    lines.push("| Brick | Sub-path | Edge | Length (pymu) | From | To |");
    lines.push("|---|---|---|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | " + f.sub_path + " | " + f.edge_index +
                   " → " + (f.edge_index + 1) + " | " + f.edge_len_pymu.toFixed(3) +
                   " | " + fmtPt(f.from) + " | " + fmtPt(f.to) + " |");
    }
};

TABLE_RENDERERS.multi_object_layer = function (lines, arr) {
    lines.push("| Brick | Sub-paths | Disjoint bbox pairs |");
    lines.push("|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | " + f.sub_path_count + " | " +
                   fmtPairs(f.disjoint_pairs) + " |");
    }
};

TABLE_RENDERERS.multi_grid_drift = function (lines, arr) {
    lines.push("| Axis | Range | Span (pymu) | Brick count | Distinct values |");
    lines.push("|---|---|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        var range = f.cluster_min.toFixed(3) + " .. " + f.cluster_max.toFixed(3);
        lines.push("| " + f.axis + " | " + range + " | " + f.span_pymu.toFixed(3) +
                   " | " + f.bricks.length + " | " + fmtDistinct(f.distinct_values) + " |");
    }
};

TABLE_RENDERERS.intra_brick_drift = function (lines, arr) {
    lines.push("| Brick | Axis | Span (pymu) | Distinct values |");
    lines.push("|---|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | " + f.axis + " | " + f.span_pymu.toFixed(3) +
                   " | " + fmtDistinct(f.distinct_values) + " |");
    }
};

TABLE_RENDERERS.corner_jitter = function (lines, arr) {
    lines.push("| Brick A | Brick B | Distance (pymu) | At |");
    lines.push("|---|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | `" + f.other_brick + "` | " +
                   f.jitter_pymu.toFixed(3) + " | " + fmtPt(f.anchor) + " |");
    }
};

TABLE_RENDERERS.brick_bbox_contained = function (lines, arr) {
    lines.push("| Inner brick | Outer brick |");
    lines.push("|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + f.brick + "` | `" + f.container_brick + "` |");
    }
};

TABLE_RENDERERS.missing_top_layer = function (lines, arr) {
    lines.push("| Layer |");
    lines.push("|---|");
    for (var i = 0; i < arr.length; i++) {
        lines.push("| `" + arr[i].layer_path + "` |");
    }
};
TABLE_RENDERERS.empty_top_layer = TABLE_RENDERERS.missing_top_layer;

function renderGenericTable(lines, arr) {
    lines.push("| Brick | Sub-path | Message |");
    lines.push("|---|---|---|");
    for (var i = 0; i < arr.length; i++) {
        var f = arr[i];
        lines.push("| `" + (f.brick || "—") + "` | " +
                   (f.sub_path == null ? "—" : f.sub_path) + " | " + f.message + " |");
    }
}

function fmtPt(p) {
    if (!p || p.length < 2) return "—";
    return "(" + p[0].toFixed(2) + ", " + p[1].toFixed(2) + ")";
}

function fmtDistinct(d) {
    if (!d) return "—";
    var parts = [];
    for (var k in d) {
        if (!d.hasOwnProperty(k)) continue;
        parts.push(k + " ×" + d[k]);
    }
    return parts.join(", ");
}

function fmtPairs(pairs) {
    if (!pairs || pairs.length === 0) return "—";
    var parts = [];
    for (var i = 0; i < pairs.length; i++) {
        parts.push("[" + pairs[i][0] + "," + pairs[i][1] + "]");
    }
    return parts.join(" ");
}
