// ai-validate.jsx — DEV-MODE in-Illustrator entry point.
//
// Use this when you want to iterate on the script's UI / behavior
// without going through a release each time. Install once with:
//
//   sudo cp /Users/varya/house_puzzle/tools/ai-validate/ai-validate.jsx \
//       "/Applications/Adobe Illustrator 2022/Presets.localized/en_US/Scripts/ai-validate.jsx"
//
// Then File > Scripts > ai-validate. Illustrator's `do javascript file`
// re-reads the JSX from disk every invocation, and so does $.evalFile
// — edit any lib/*.jsx in the project tree, run again, changes are live.
//
// What this wrapper does:
//   1. Sets AI_VALIDATE_VERSION = "(dev)" so validate.jsx flips into
//      interactive mode (panel UI, no /tmp scaffolding reads).
//   2. Sets AI_VALIDATE_MANIFEST_URL = "" so the update-check
//      short-circuits — no spurious "newer version available" alerts
//      from the launchd-populated cache that an earlier .pkg install
//      may have left behind.
//   3. $.evalFile()s validate.jsx from the same directory (or the
//      hardcoded project path as a fallback).
//
// The PRODUCTION entry point shipped to artists is the bundled
// .jsx generated by packaging/bundle.sh — it's a single self-contained
// file that injects real version constants. Don't confuse the two:
// THIS wrapper is for the developer's machine only.

#target illustrator
// ScriptUI palette() windows are destroyed the moment their host
// script's engine context tears down. Without a named engine, the
// wrapper's main runs on the default one-shot engine, $.evalFile
// returns, the engine dies, and the panel disappears before the
// artist ever sees it ("I ran the script, nothing happened").
// "session" lifetime keeps the engine alive for the rest of the
// Illustrator session — palette + its onClick closures remain
// usable. Re-running the script reuses the same engine.
#targetengine "ai-validate-panel"

var AI_VALIDATE_VERSION = "(dev)";
var AI_VALIDATE_MANIFEST_URL = "";

(function () {
    var here = File($.fileName).parent;
    var sibling = File(here.fsName + "/validate.jsx");
    var fallback = File("/Users/varya/house_puzzle/tools/ai-validate/validate.jsx");
    var validateJsx = sibling.exists ? sibling : fallback;
    if (!validateJsx.exists) {
        alert("ai-validate (dev): can't find validate.jsx.\n\nTried:\n  " +
              sibling.fsName + "\n  " + fallback.fsName);
        return;
    }
    $.evalFile(validateJsx);
})();
